/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MGDAbi } from "./MGDAbi";
export * as factories from "./factories";
export { MGDAbi__factory } from "./factories/MGDAbi__factory";
